spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.13.15:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  # 配置redis共享
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    session:
      timeout: 30m
  port: 8090